name: form_submit_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  flutter_spinkit: ^5.2.2
  intl: ^0.20.2
  url_launcher: ^6.3.2
  mask_text_input_formatter: ^2.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon2.png"
  adaptive_icon_foreground: "assets/images/app-icon2.png"
  adaptive_icon_background: "#FFFFFF"   # âœ… Use valid hex color, not "none"



flutter:
  uses-material-design: true

  assets:
    - assets/images/
